Update Atlas to remove Ray and add a fastapi that supports batching (#11)

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -71,7 +71,12 @@ jobs:
             test_activity pytest tests/integration/inference/atlas_activity/ -vv
       - name: Run service tests
         run: |
-          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f ais/docker-compose.yml up -d --wait
+          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f ais/docker-compose.yml up -d --wait || {
+            echo "🚨 Containers failed to start! Printing logs..."
+            docker ps -a
+            docker compose -f ais/docker-compose.yml logs
+            exit 1
+          }
           sleep 20
           docker compose -f ais/docker-compose.yml exec -T \
             -e TEST_PROJECTS_FOLDER_PREFIX=${{ secrets.TEST_PROJECTS_FOLDER_PREFIX }} \
